### ISSUE TITLE
[Suggestion] Implement username/password authentication

### ISSUE THREAD

**Issue by uhidontkno** [spaceness/stardust#16]
Should be fairly straightforward for NextAuth.js, implementing user/pass auth will allow people to BYOD easier.

**Comment by yosoof3** [comment]
> Should be fairly straightforward for NextAuth.js, implementing user/pass auth will allow people to BYOD easier.

bro this would mean we would have to do breaking changes to the schema because we would have to do email/pass auth because if the user forgets there pass we are cooked. SPEAKING OF WHICH WE NEED SMTP

**Comment by IncognitoTGT** [comment]
smtp is hell in nodejs

ive gotten it to work but thats more work for the end user

**Comment by IncognitoTGT** [comment]
Ok to be fair kasm doesn't use SMTP and it relies on the admin to reset password so this is still a possibility

**Comment by uhidontkno** [comment]
> smtp is hell in nodejs
auth.js has a built in credential thingy

**Comment by uhidontkno** [comment]
> > Should be fairly straightforward for NextAuth.js, implementing user/pass auth will allow people to BYOD easier.
> 
> bro this would mean we would have to do breaking changes to the schema because we would have to do email/pass auth because if the user forgets there pass we are cooked. SPEAKING OF WHICH WE NEED SMTP

how about you just dont accept reset password and just let the admin do it

**Comment by IncognitoTGT** [comment]
yes, it's gonna require storing stuff in the db

**Comment by IncognitoTGT** [comment]
> > > Should be fairly straightforward for NextAuth.js, implementing user/pass auth will allow people to BYOD easier.
> > 
> > 
> > bro this would mean we would have to do breaking changes to the schema because we would have to do email/pass auth because if the user forgets there pass we are cooked. SPEAKING OF WHICH WE NEED SMTP
> 
> how about you just dont accept reset password and just let the admin do it


yeah thats what im thinking of

**Comment by uhidontkno** [comment]
> > how about you just dont accept reset password and just let the admin do it
> 
> yeah thats what im thinking of

as auth0 was implemented first, that means stardust was not meant to have a public instance with an easy community links system. this also applies to kasm, kasm was made for businesses which is the reason why there are stupendous licensing fees that are not consumer friendly.

**Comment by uhidontkno** [comment]
also why use gh as an issue tracker for something closed source, either use something proprietary or just open source your shit

**Comment by IncognitoTGT** [comment]
a lot of companies do that

some like vercel use linear for stuff like that lol


anyways this is added to the roadmap and auth0 will be dumped in the next release of Stardust

**Comment by IncognitoTGT** [comment]
update:
 more oauth providers added, user/pass would f a lot of the things

**Comment by uhidontkno** [comment]
> update: more oauth providers added, user/pass would f a lot of the things

bruh

**Comment by uhidontkno** [comment]
auth.js literally supports username/pass and it would probably not fuck much shit up
