### ISSUE TITLE
Why remove Xpra? 

### ISSUE THREAD

**Issue by gitizenss** [spaceness/stardust#23]
I get it's that typescript library is a pain, but why remove it instead of switching to the official js one? I think it gives too much freedom to ignore, especially when combined with https://github.com/selkies-project/selkies-xpra which would enable advanced graphics / realtime gameplay etc.

**Comment by IncognitoTGT** [comment]
The official JS one is the exact same thign without TS. the issues ive been having have to do with react being super weird. 
I might look into it later when I have motivation as i currently have school to deal with
