### ISSUE TITLE
Container fails to create if user has specials in email

### ISSUE THREAD

**Issue by tuta-amb** [spaceness/stardust#6]
As can be observed in this screenshot ([source [discord]](https://discord.com/channels/1131443208216399912/1239000671135727636/1240473047941517383), credit: @IncognitoTGT):
![image](https://github.com/spaceness/stardust/assets/146651411/571f981d-4094-4f1c-9b7f-05e19e3a2990)
Upon attempting to start a container when the user in question has specials symbols, ie. `+`, the container fails to create.

This issue appears stem from this [line](https://github.com/spaceness/stardust/blob/ffea4055f6c76969c0d8f2e1142299eef0d81570/src/lib/session/index.ts#L35), where a Docker container is being created with an ID that involves the user's email local hostname being appended to the end. As Docker container names are not permitted to have symbols such as `+`, this causes the aforementioned error, and renders the application entirely unusable for users with symbols in their email.

**Comment by IncognitoTGT** [comment]
Can you please pr a fix for this as very few people are gonna use a + alias with their emails. 

- @IncognitoTGT

**Comment by tuta-amb** [comment]
@IncognitoTGT Working on it. :shipit:
